# This workflow checks the links in plaintext files in the repository
name: Check Links

on:
  # Uncomment the 'pull_request' line below to trigger the workflow in PR
  # pull_request:
  # Schedule runs on 12 noon every Sunday
  schedule:
    - cron: '0 12 * * 0'

jobs:
  check_links:
    name: Check Links
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2.3.4

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.0.4
      with:
        # 429: Too many requests
        args: >
          --accept 429
          --exclude "^ftp://"
          --exclude "^https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$"
          --exclude "^https://download1.rpmfusion.org/free/el/rpmfusion-free-release-$"
          --exclude "^http://maps.google.com/mapfiles/kml/$"
          --exclude "^http://aa.usno.navy.mil/faq/docs/lawyers.php$"
          --exclude "^Uhttp://my.server.com/images$"
          --exclude "^-W@weight.png$"
          --verbose
          "**/*.rst"
          "**/*.rst_"
          "**/*.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2.3.2
      with:
        title: Link Checker Report
        content-filepath: ./lychee/out.md
