#
# Create an issue to remind us some important things.
#
# It's scheduled to run every 6 months.
#
name: Reminders

on:
  workflow_dispatch:
  # Scheduled to run at midnight on the 1st day every 6 months
  schedule:
    - cron: '0 0 1 */6 *'

jobs:
  review-known-failures:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Find and report known failures
      run: |
        # Get the list of known failures
        KNOWN_FAILURES=$(grep -rl 'GMT_KNOWN_FAILURE' test/**/*.sh)

        # If there are known failures, create an issue
        if [ -n "$KNOWN_FAILURES" ]; then
          title="Review GMT's known failures"

          echo "The following tests are marked as GMT_KNOWN_FAILURE and need review:" > report.md
          echo "" >> report.md
          while IFS= read -r line ; do echo "1. $line"; done <<< $KNOWN_FAILURES >> report.md

          gh issue create --title "$title" --body-file report.md
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

